<?php

return [
  'contact_FullFirst' => [
    'name'        => 'contact_FullFirst',
    'type'        => 'Boolean',
    'html_type'   => 'checkbox',
    'default'     => TRUE,
    'title'       => ts('Capitalize first letter of each word in all names'),
    'description' => '',
    'is_domain'   => 1,
    'is_contact'  => 0,
  ],
  'contact_OrgCaps' => [
    'name'        => 'contact_OrgCaps',
    'type'        => 'Boolean',
    'html_type'   => 'checkbox',
    'default'     => FALSE,
    'title'       => ts('Capitalize organization names'),
    'description' => '',
    'is_domain'   => 1,
    'is_contact'  => 0,
  ],
  'phone_normalize' => [
    'name'        => 'phone_normalize',
    'type'        => 'Boolean',
    'html_type'   => 'checkbox',
    'default'     => TRUE,
    'title'       => ts('Normalize phone numbers'),
    'description' => '',
    'is_domain'   => 1,
    'is_contact'  => 0,
  ],
  'phone_IntlPrefix' => [
    'name'        => 'phone_IntlPrefix',
    'type'        => 'Boolean',
    'html_type'   => 'checkbox',
    'default'     => TRUE,
    'title'       => ts('Normalize local numbers as International'),
    'description' => '',
    'is_domain'   => 1,
    'is_contact'  => 0,
  ],
  'address_CityCaps' => [
    'name'        => 'address_CityCaps',
    'type'        => 'Integer',
    'html_type'   => 'text',
    'default'     => 0,
    'title'       => ts('Capitalization options for city names'),
    'description' => '',
    'is_domain'   => 1,
    'is_contact'  => 0,
  ],
  'address_StreetCaps' => [
    'name'        => 'address_StreetCaps',
    'type'        => 'Integer',
    'html_type'   => 'text',
    'default'     => 0,
    'title'       => ts('Capitalization options for street addresses'),
    'description' => '',
    'is_domain'   => 1,
    'is_contact'  => 0,
  ],
  'address_Zip' => [
    'name'        => 'address_Zip',
    'type'        => 'Boolean',
    'html_type'   => 'checkbox',
    'default'     => TRUE,
    'title'       => ts('Normalize zip codes and flag incorrect entries'),
    'description' => '',
    'is_domain'   => 1,
    'is_contact'  => 0,
  ],
];
